<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 * Created: %s
 */
class %s extends Doctrine_Record
{
    public function setTableDefinition()
    {
%s
    }
    public function setUp()
    {

    }
}
