<?php
// auto-generated by sfRoutingConfigHandler
// date: 2007/08/31 18:35:26
$routes = sfRouting::getInstance();
$routes->setRoutes(
array (
  'homepage' => 
  array (
    0 => '/',
    1 => '/^[\\/]*$/',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'main',
      'action' => 'index',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'api_documentation_page' => 
  array (
    0 => '/documentation/api/:q',
    1 => '#^/documentation/api(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'q',
    ),
    3 => 
    array (
      'q' => 1,
    ),
    4 => 
    array (
      'module' => 'api_documentation',
      'action' => 'index',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'about' => 
  array (
    0 => '/about',
    1 => '#^/about$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'main',
      'action' => 'about',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'download' => 
  array (
    0 => '/download',
    1 => '#^/download$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'main',
      'action' => 'download',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'manual' => 
  array (
    0 => '/documentation/manual',
    1 => '#^/documentation/manual$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'manual',
      'action' => 'index',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'api_documentation' => 
  array (
    0 => '/documentation/api',
    1 => '#^/documentation/api$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'api_documentation',
      'action' => 'index',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'trac' => 
  array (
    0 => '/trac',
    1 => '#^/trac$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'main',
      'action' => 'trac',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'default_symfony' => 
  array (
    0 => '/symfony/:action/*',
    1 => '#^/symfony(?:\\/([^\\/]+))?(?:\\/(.*))?$#',
    2 => 
    array (
      0 => 'action',
    ),
    3 => 
    array (
      'action' => 1,
    ),
    4 => 
    array (
      'module' => 'default',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'default_index' => 
  array (
    0 => '/:module',
    1 => '#^(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'module',
    ),
    3 => 
    array (
      'module' => 1,
    ),
    4 => 
    array (
      'action' => 'index',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'default' => 
  array (
    0 => '/:module/:action/*',
    1 => '#^(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?(?:\\/(.*))?$#',
    2 => 
    array (
      0 => 'module',
      1 => 'action',
    ),
    3 => 
    array (
      'module' => 1,
      'action' => 1,
    ),
    4 => 
    array (
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
)
);
