<?php
// auto-generated by sfViewConfigHandler
// date: 2007/08/31 18:35:26
$context  = $this->getContext();
$response = $context->getResponse();


  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (!$context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Doctrine - Open Source PHP 5 ORM', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Doctrine is a Open Source OO PHP 5 ORM', false, false);
  $response->addMeta('keywords', 'doctrine, php, database, orm', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('main', '', array ());
  $response->addStylesheet('layout', '', array ());
  $response->addStylesheet('manual', '', array ());
  $response->addJavascript('manual_toc');
  $response->addJavascript('manual_tree');
  $response->addJavascript('mootools.v1.11');


