<?php
// auto-generated by sfDoctrineConfigHandler
// date: 2007-08-31 10:38:25
$default_attributes["ATTR_EXPORT"] = Doctrine::EXPORT_ALL;
$default_attributes["ATTR_FETCHMODE"] = Doctrine::FETCH_IMMEDIATE;
$default_attributes["ATTR_COLL_LIMIT"] = 5;
$default_attributes["ATTR_LOCKMODE"] = Doctrine::LOCK_PESSIMISTIC;
$default_attributes["ATTR_VLD"] = false;
$default_attributes["ATTR_QUOTE_IDENTIFIER"] = false;

