<?php
require_once('generated/BaseContact.class.php');
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Contact extends BaseContact
{

	public function setTableDefinition()
	{
				parent::setTableDefinition();
	}

	public function setUp()
	{
				parent::setUp();
	}

}