<?php
/*
 * Edit this file to customise your model class
 *
 * auto-generated by the sfDoctrine plugin
 */
class BlogPost extends BaseBlogPost
{
  public function filterSetName($name)
  {
    $this->setSlug(Common::createSlug($name));
    
    return $name;
  }
}
