on:
  pull_request:
  push:
    branches:
      - master
jobs:
  coding-standards:
    name: "Coding Standards"
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2'
        extensions: mbstring
        tools: composer, cs2pr

    - name: composer install
      run: "composer install --no-progress --no-suggest --no-interaction --prefer-dist --optimize-autoloader"

    - name: phpcs
      run: "php vendor/bin/phpcs -q --report=checkstyle --no-colors | cs2pr"

  static-analysis:
    name: "Static Analysis"
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2'
        extensions: mbstring
        tools: composer, cs2pr

    - name: composer install
      run: "composer install --no-progress --no-suggest --no-interaction --prefer-dist --optimize-autoloader"

    - name: phpstan
      run: "php vendor/bin/phpstan analyse --error-format=checkstyle --no-progress | cs2pr"
